name: nucleus2_moe_divfree
train_module_name: divfree_forecast
layout: "t h w c"
params:
  patch_size: 4
  embed_dim: 512
  moe_intermediate_dim: 1024
  processor_blocks: 12
  num_heads: 8
  num_experts: 6
  topk: 2
  patching: "Linear"
  activation_dtype: "bfloat16"