log_dir: /pub/afeeney/bubbleformer_logs
seed: 42

nodes: 1
devices: 1

max_epochs:
max_steps: 100000
val_check_interval: 5000
batch_size: 16
accumulate_grad_batches: 1

history_time_window: 1
future_time_window: 1
time_step: 1
start_time: 100

layout: "t c h w"

checkpoint_path:
commit_sha:
  
optim_cfg:
  name: adamw
  params:
    lr: 3e-4
    weight_decay: 0.1

defaults:
  - _self_
  - model_cfg: poseidon_big
  - data_cfg: poolboiling64
  - scheduler_cfg: cosine_warmup
  - normalizer_cfg: no